//! A seccomp-bpf syscall denylist for sandboxed steps.
//!
//! This is defence in depth, additive to the mount/pid/net namespaces, the
//! Landlock filesystem ruleset, `no_new_privs` and the unprivileged uid. The
//! confined process already cannot gain privilege; the filter makes the
//! kernel attack surface it can reach explicit by refusing a fixed set of
//! administrative and exploit-primitive syscalls with `EPERM`.
//!
//! A denylist (default-allow) rather than an allowlist is deliberate: an
//! allowlist that misses one syscall breaks ordinary build tools, whereas the
//! denied calls here are never issued by a normal `process` step.
//!
//! The BPF program is generated by `seccompiler` for the running
//! architecture (x86_64, aarch64 or riscv64); a syscall made under any other
//! audit architecture (e.g. the 32-bit x86 ABI) kills the process. Syscall
//! numbers come from `libc::SYS_*`, so they are correct for the target.

use nix::errno::Errno;
use nix::libc;
use seccompiler::{BpfProgram, SeccompAction, SeccompFilter, SeccompRule, TargetArch};
use std::collections::BTreeMap;
use std::io;

/// Syscalls a `process` step is never expected to make and that are classic
/// escape or tamper primitives. Each is cap-gated or namespace-sensitive; the
/// filter denies them regardless of the running uid's capabilities.
fn denied() -> Vec<libc::c_long> {
    vec![
        libc::SYS_mount,
        libc::SYS_umount2,
        libc::SYS_pivot_root,
        libc::SYS_setns,
        libc::SYS_unshare,
        libc::SYS_init_module,
        libc::SYS_finit_module,
        libc::SYS_delete_module,
        libc::SYS_kexec_load,
        libc::SYS_kexec_file_load,
        libc::SYS_bpf,
        libc::SYS_ptrace,
        libc::SYS_perf_event_open,
        libc::SYS_keyctl,
        libc::SYS_add_key,
        libc::SYS_request_key,
        libc::SYS_reboot,
        libc::SYS_swapon,
        libc::SYS_swapoff,
        libc::SYS_acct,
        libc::SYS_quotactl,
        libc::SYS_clock_settime,
        libc::SYS_clock_adjtime,
        libc::SYS_adjtimex,
    ]
}

/// A compiled filter, ready to install.
pub struct Filter {
    prog: BpfProgram,
}

impl Filter {
    /// Compile the denylist for the running architecture.
    pub fn compile() -> io::Result<Filter> {
        let arch = TargetArch::try_from(std::env::consts::ARCH).map_err(io::Error::other)?;
        // An empty rule list matches the syscall unconditionally.
        let rules: BTreeMap<i64, Vec<SeccompRule>> = denied().into_iter().map(|nr| (nr, vec![])).collect();
        let filter = SeccompFilter::new(rules, SeccompAction::Allow, SeccompAction::Errno(Errno::EPERM as u32), arch)
            .map_err(io::Error::other)?;
        let prog = BpfProgram::try_from(filter).map_err(io::Error::other)?;
        Ok(Filter { prog })
    }

    /// Install the filter on the calling thread (setting `no_new_privs`
    /// first). Call it last before `exec`, in the process being confined.
    /// Returns an error if the kernel cannot apply a filter, so the caller
    /// can fail closed.
    pub fn install(&self) -> io::Result<()> {
        seccompiler::apply_filter(&self.prog).map_err(io::Error::other)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn denylist_has_no_duplicates() {
        let mut nrs = denied();
        let n = nrs.len();
        nrs.sort_unstable();
        nrs.dedup();
        assert_eq!(nrs.len(), n);
    }

    #[test]
    fn filter_compiles_for_this_arch() {
        let f = Filter::compile().unwrap();
        // At least one comparison per denied syscall.
        assert!(f.prog.len() > denied().len(), "program too short: {}", f.prog.len());
    }
}
